const reparacoes = [
  { id: 1, device: "Samsung Galaxy S22 Ultra", brand: "Samsung", problem: "Ecrã partido, já nem dava imagem", solution: "Substituição de ecrã original Samsung", price: "a partir de 200€", time: "45 min", photos: [{ before: "assets/reparacoes/samsung-s22-ultra/frente-antes.jpg", after: "assets/reparacoes/samsung-s22-ultra/frente-depois.jpg", label: "Frente" }] },
  { id: 2, device: "iPhone 14 Pro Max", brand: "Apple", problem: "Caiu de alta altitude, traseira toda partida", solution: "Substituição de vidro traseiro", price: "a partir de 55€", time: "1h30", photos: [{ before: "assets/reparacoes/iphone-14-pro-max/traseira-antes.jpg", after: "assets/reparacoes/iphone-14-pro-max/traseira-depois.jpg", label: "Traseira" }] },
  { id: 3, device: "iPhone 12 Pro Max", brand: "Apple", problem: "Bateria a 70%, ecrã partido e traseira partida", solution: "Bateria nova, ecrã Soft OLED e vidro traseiro novo", price: "a partir de 150€", time: "2h", photos: [{ before: "assets/reparacoes/iphone-12-pro-max/frente-antes.jpg", after: "assets/reparacoes/iphone-12-pro-max/frente-depois.jpg", label: "Frente" }, { before: "assets/reparacoes/iphone-12-pro-max/traseira-antes.png", after: "assets/reparacoes/iphone-12-pro-max/traseira-depois.jpg", label: "Traseira" }] },
  { id: 4, device: "iPhone 11", brand: "Apple", problem: "Traseira e laterais danificadas, ecrã danificado", solution: "Ecrã novo, bateria nova e chassis novo (mudou de vermelho para branco a pedido do cliente)", price: "a partir de 100€", time: "2h", photos: [{ before: "assets/reparacoes/iphone-11/frente-antes.jpg", after: "assets/reparacoes/iphone-11/frente-depois.jpg", label: "Frente" }, { before: "assets/reparacoes/iphone-11/traseira-antes.jpg", after: "assets/reparacoes/iphone-11/traseira-depois.jpg", label: "Traseira" }] },
  { id: 5, device: "iPhone X", brand: "Apple", problem: "Um carro passou por cima do telemóvel", solution: "Ecrã novo, chassis lateral e vidro traseiro novo", price: "a partir de 95€", time: "2h", photos: [{ before: "assets/reparacoes/iphone-x/frente-antes.jpg", after: "assets/reparacoes/iphone-x/frente-depois.jpg", label: "Frente" }, { before: "assets/reparacoes/iphone-x/traseira-antes.jpg", after: "assets/reparacoes/iphone-x/traseira-depois.jpg", label: "Traseira" }] },
  { id: 6, device: "iPhone 8", brand: "Apple", problem: "Um carro passou por cima, ecrã partido, chassis empenado e vidro traseiro partido", solution: "Ecrã novo e chassis novo", price: "a partir de 90€", time: "2h", photos: [{ before: "assets/reparacoes/iphone-8/antes.jpg", after: "assets/reparacoes/iphone-8/depois.jpg", label: "Completo" }] },
  { id: 7, device: "Samsung S23 Ultra", brand: "Samsung", problem: "Ecrã partido", solution: "Ecrã compatível com película de gel (opção económica)", price: "a partir de 130€", time: "45 min", photos: [{ before: "assets/reparacoes/samsung-s23-ultra/traseira-antes.jpg", after: "assets/reparacoes/samsung-s23-ultra/frente-depois.jpg", label: "Frente" }] },
  { id: 8, device: "Oppo", brand: "Oppo", problem: "Traseira riscada, vidro da câmera partido e ecrã partido", solution: "Traseira nova (cor diferente a pedido do cliente) e ecrã novo", price: "a partir de 70€", time: "1h", photos: [{ before: "assets/reparacoes/oppo/antes.jpg", after: "assets/reparacoes/oppo/depois.jpg", label: "Completo" }] },
  { id: 9, device: "CrossCall", brand: "CrossCall", problem: "Ecrã partido", solution: "Substituição de ecrã novo", price: "a partir de 50€", time: "1h", photos: [{ before: "assets/reparacoes/crosscall/antes.jpg", after: "assets/reparacoes/crosscall/depois.png", label: "Frente" }] },
  { id: 10, device: "Lenovo Tablet", brand: "Lenovo", problem: "Ecrã partiu, deixou de dar imagem", solution: "Substituição do vidro do tablet", price: "a partir de 85€", time: "1h", photos: [{ before: "assets/reparacoes/lenovo-tablet/antes.png", after: "assets/reparacoes/lenovo-tablet/depois.jpg", label: "Frente" }] },
  { id: 11, device: "iPhone 13 Pro", brand: "Apple", problem: "Vidro traseiro partido", solution: "Vidro traseiro novo", price: "a partir de 55€", time: "1h30", photos: [{ before: "assets/reparacoes/iphone-13-pro/traseira-antes.jpg", after: "assets/reparacoes/iphone-13-pro/traseira-depois.jpg", label: "Traseira" }] },
  { id: 12, device: "iPhone 13 (traseira)", brand: "Apple", problem: "Vidro traseiro partido", solution: "Vidro traseiro novo", price: "a partir de 55€", time: "1h30", photos: [{ before: "assets/reparacoes/iphone-13/traseira-antes.png", after: "assets/reparacoes/iphone-13/traseira-depois.png", label: "Traseira" }] },
  { id: 13, device: "iPhone 13 (ecrã)", brand: "Apple", problem: "Ecrã partido", solution: "Ecrã novo", price: "a partir de 70€", time: "45 min", photos: [{ before: "assets/reparacoes/outro-iphone-13/frente-antes.jpg", after: "assets/reparacoes/outro-iphone-13/frente-depois.jpg", label: "Frente" }] },
  { id: 14, device: "iPhone 6 Plus", brand: "Apple", problem: "Ecrã partido", solution: "Ecrã novo", price: "a partir de 45€", time: "45 min", photos: [{ before: "assets/reparacoes/iphone-6-plus/frente-antes.jpg", after: "assets/reparacoes/iphone-6-plus/frente-depois.png", label: "Frente" }] },
  { id: 15, device: "Samsung A02", brand: "Samsung", problem: "Ecrã todo partido, já nem dava imagem", solution: "Ecrã novo", price: "desde 45€", time: "45 min", photos: [{ before: "assets/reparacoes/samsung-a02/frente-antes.jpg", after: "assets/reparacoes/samsung-a02/frente-depois.png", label: "Frente" }] },
  { id: 16, device: "Samsung A21s", brand: "Samsung", problem: "Ecrã partido", solution: "Ecrã novo", price: "desde 45€", time: "45 min", photos: [{ before: "assets/reparacoes/samsung-a21s/frente-antes.jpg", after: "assets/reparacoes/samsung-a21s/frente-depois.jpg", label: "Frente" }] },
  { id: 17, device: "Samsung A02s", brand: "Samsung", problem: "Ecrã partido", solution: "Ecrã novo", price: "a partir de 45€", time: "45 min", photos: [{ before: "assets/reparacoes/samsung-a02s/frente-antes.jpg", after: "assets/reparacoes/samsung-a02s/frente-depois.jpg", label: "Frente" }] },
  { id: 18, device: "Xiaomi 13C", brand: "Xiaomi", problem: "Ecrã partido", solution: "Ecrã novo", price: "a partir de 45€", time: "45 min", photos: [{ before: "assets/reparacoes/xiaomi-13c/frente-antes.jpg", after: "assets/reparacoes/xiaomi-13c/frente-depois.jpg", label: "Frente" }] },
  { id: 19, device: "Xiaomi Mi 9", brand: "Xiaomi", problem: "Vidro traseiro partido", solution: "Vidro traseiro novo", price: "a partir de 40€", time: "45 min", photos: [{ before: "assets/reparacoes/xiaomi-mi-9/traseira-antes.jpg", after: "assets/reparacoes/xiaomi-mi-9/traseira-depois.jpg", label: "Traseira" }] },
];

const videos = [
  { id: "E_h5DjCnnss", title: { pt: "Reparação do Vidro Traseiro - iPhone 13 Pro", en: "Back Glass Repair - iPhone 13 Pro" }, description: { pt: "Processo completo de substituição do vidro traseiro na LopesTech", en: "Complete back glass replacement process at LopesTech" } },
  { id: "OnKtv0bGWBg", title: { pt: "Reparação Completa - iPhone 15 Pro", en: "Complete Repair - iPhone 15 Pro" }, description: { pt: "Processo completo de reparação na LopesTech", en: "Complete repair process at LopesTech" } },
  { id: "QjtyUNCyMd0", title: { pt: "Ecrã, Bateria e Chassis - iPhone 8", en: "Screen, Battery and Chassis - iPhone 8" }, description: { pt: "Substituição completa de ecrã, bateria e chassis na LopesTech", en: "Complete screen, battery and chassis replacement at LopesTech" } },
  { id: "KoIj4a6GTwc", title: { pt: "iPhone XR - Antes e Depois", en: "iPhone XR - Before and After" }, description: { pt: "Reparação completa de iPhone XR — chassis novo e ecrã novo", en: "Complete iPhone XR repair — new chassis and screen" } },
];

const featuredProject = {
  title: "eBL Middleware — Blockchain & Digital Supply Chain",
  description: {
    pt: "Sistema middleware empresarial que revoluciona o transporte marítimo ao digitalizar os Bill of Lading (BL) para Electronic Bill of Lading (EBL) na blockchain. Elimina os BLs em papel — cada edição, transferência ou aprovação de levantamento é registada de forma imutável e rastreável. As empresas (carriers, shippers, consignees) têm contratos e carteiras na blockchain, garantindo segurança, confiança e rapidez em cada operação. Cada EBL recebe um token ID único, assegurando total transparência na digital supply chain. Um passo decisivo na transição para o Web3 nos transportes internacionais.",
    en: "Enterprise middleware system revolutionizing maritime transport by digitizing Bills of Lading (BL) into Electronic Bills of Lading (EBL) on the blockchain. Eliminates paper BLs — every edit, transfer or pickup approval is immutably recorded and traceable. Companies (carriers, shippers, consignees) have contracts and wallets on the blockchain, ensuring security, trust and speed in every operation. Each EBL receives a unique token ID, ensuring total transparency in the digital supply chain. A decisive step in the Web3 transition for international shipping.",
  },
  tags: [".NET 10", "React", "SQL Server", "Blockchain", "Web3", "Python"],
  images: ["assets/projetos/blockchain1.png", "assets/projetos/blockchain2.png", "assets/projetos/blockchain3.png"],
};

const projects = [
  { title: "NextHire — Portal de Emprego", description: { pt: "Portal de emprego full-stack MERN. Employers publicam vagas, candidatos pesquisam e gerem candidaturas.", en: "Full-stack MERN job portal. Employers post jobs, candidates search and manage applications." }, tags: ["MongoDB", "Express", "React", "Node.js", "Tailwind CSS"], link: "https://next-hire-ashen.vercel.app", github: "https://github.com/brunolopes9/NextHire", image: "https://raw.githubusercontent.com/brunolopes9/NextHire/main/frontend/NextHire/public/1.png" },
  { title: "RankingApp — Classificador Interativo", description: { pt: "Aplicação interativa com drag & drop para classificar filmes ou álbuns. Full-stack com React e ASP.NET Core.", en: "Interactive drag & drop app for ranking movies or albums. Full-stack with React and ASP.NET Core." }, tags: ["React", "ASP.NET Core", "C#", "Tailwind CSS"], github: "https://github.com/brunolopes9/rankingApp", image: "https://raw.githubusercontent.com/brunolopes9/rankingApp/main/rankingapp.client/public/RankingApp1.png" },
  { title: "SimpleShop — E-Commerce", description: { pt: "E-commerce com múltiplas bases de dados: MySQL, MongoDB e Redis. Segurança com Argon2.", en: "E-commerce with multiple databases: MySQL, MongoDB and Redis. Security with Argon2." }, tags: ["Fastify", "MySQL", "MongoDB", "Redis"], github: "https://github.com/brunolopes9/SimpleShop", image: "https://raw.githubusercontent.com/brunolopes9/SimpleShop/main/public/1.png" },
  { title: "BLE Tracking System", description: { pt: "Sistema de rastreamento industrial com BLE. Projeto em parceria com HUF Portuguesa.", en: "Industrial tracking system with BLE. Project in partnership with HUF Portuguesa." }, tags: ["Node.js", "PHP", "MQTT", "BLE"], github: "https://github.com/brunolopes9/ble_tracking_system" },
  { title: "BrunoFolio — Portfólio", description: { pt: "Portfólio pessoal moderno com dark mode, animações e formulário de contacto com API.", en: "Modern personal portfolio with dark mode, animations and contact form with API." }, tags: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"], link: "https://bruno-folio-8y1g.vercel.app/", github: "https://github.com/brunolopes9/BrunoFolio" },
  { title: "DevLinks — Cartão Digital", description: { pt: "Cartão de visitas digital interativo com links para redes sociais e contacto.", en: "Interactive digital business card with social media and contact links." }, tags: ["HTML", "CSS", "JavaScript"], link: "https://brunolopes9.github.io/DevLinks/", github: "https://github.com/brunolopes9/DevLinks" },
  { title: "Bulky MVC — Gestão", description: { pt: "Aplicação MVC para gestão de produtos com CRUD completo e autorização por roles.", en: "MVC application for product management with full CRUD and role-based authorization." }, tags: ["ASP.NET Core", "C#", "SQL Server"], github: "https://github.com/brunolopes9/Bulky_MVC" },
  { title: "netCRUD — API REST", description: { pt: "API RESTful com CRUD completo demonstrando boas práticas de backend.", en: "RESTful API with full CRUD demonstrating backend best practices." }, tags: [".NET", "C#", "REST API"], github: "https://github.com/brunolopes9/netCRUD" },
  { title: "myTodo — Tarefas", description: { pt: "Gestor de tarefas com Redux Toolkit, Thunks assíncronos e REST API.", en: "Task manager with Redux Toolkit, async Thunks and REST API." }, tags: ["React", "Redux", "Express"], github: "https://github.com/brunolopes9/myTodo" },
  { title: "TypingSpeed", description: { pt: "Teste de velocidade de escrita com medição de palavras por minuto em tempo real.", en: "Typing speed test with real-time words per minute measurement." }, tags: ["JavaScript", "CSS"], link: "https://brunolopes9.github.io/TypingSpeed/", github: "https://github.com/brunolopes9/TypingSpeed" },
  { title: "TrainTwitter", description: { pt: "Clone simplificado do Twitter com funcionalidades de publicação e feed.", en: "Simplified Twitter clone with posting and feed features." }, tags: ["JavaScript", "CSS"], link: "https://brunolopes9.github.io/TrainTwitter/", github: "https://github.com/brunolopes9/TrainTwitter" },
  { title: "MoonWalk", description: { pt: "Landing page temática com animações e design imersivo.", en: "Themed landing page with animations and immersive design." }, tags: ["HTML", "CSS", "JavaScript"], link: "https://brunolopes9.github.io/MoonWalk/", github: "https://github.com/brunolopes9/MoonWalk" },
  { title: "Clock", description: { pt: "Relógio digital interativo com design moderno.", en: "Interactive digital clock with modern design." }, tags: ["HTML", "CSS", "JavaScript"], link: "https://brunolopes9.github.io/clock/", github: "https://github.com/brunolopes9/clock" },
];

const techStack = [
  { name: ".NET / C#", color: "text-purple-600" },
  { name: "React", color: "text-cyan-500", faIcon: "fa-brands fa-react" },
  { name: "TypeScript", color: "text-blue-600" },
  { name: "MongoDB", color: "text-green-600" },
  { name: "Python", color: "text-yellow-500", faIcon: "fa-brands fa-python" },
  { name: "Tailwind", color: "text-teal-500" },
  { name: "SQL Server", color: "text-red-600", faIcon: "fa-solid fa-database" },
];
